### ISSUE TITLE
ModuleNotFoundError: No module named 'confuse'

### ISSUE THREAD

**Issue by MartenBE** [adamjakab/BeetsPluginYearFixer#6]
### Problem

Running your command in verbose (`-vv`) mode:

```sh
$ beet -vv yearfixer
user configuration: /home/martijn/.config/beets/config.yaml
data directory: /home/martijn/.config/beets
plugin paths:
** error loading plugin yearfixer:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/beets/plugins.py", line 273, in load_plugins
    namespace = __import__(modname, None, None)
  File "/usr/local/lib/python3.10/site-packages/beetsplug/yearfixer/__init__.py", line 10, in <module>
    from confuse import ConfigSource, load_yaml
ModuleNotFoundError: No module named 'confuse'

Sending event: pluginload
library database: /home/martijn/.config/beets/library.db
library directory: /home/martijn/beets-music
Sending event: library_opened
error: unknown command 'yearfixer'
```

Led to this problem:

```
$ sudo pip3 install beets-yearfixer
```

### Setup

* OS: Fedora Linux 36 (Server Edition) x86_64
* Python version: 3.10.6
* Beets version: 1.4.9
* Turning off other plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
directory: ~/beets-music
plugins: duplicates replaygain chroma yearfixer
paths:
    default: $original_year/$albumartist/$album %aunique{}/$track - $title
    singleton: $original_year/$artist - $title

import:
    copy: yes
    write: yes

chroma:
    auto: yes
replaygain:
    auto: yes
    backend: gstreamer
    overwrite: yes   
```

My plugin version (output of `beet yearfixer -v`) is:

Latest through pip.

```text
user configuration: /home/martijn/.config/beets/config.yaml
data directory: /home/martijn/.config/beets
plugin paths:
** error loading plugin yearfixer:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/beets/plugins.py", line 273, in load_plugins
    namespace = __import__(modname, None, None)
  File "/usr/local/lib/python3.10/site-packages/beetsplug/yearfixer/__init__.py", line 10, in <module>
    from confuse import ConfigSource, load_yaml
ModuleNotFoundError: No module named 'confuse'

Sending event: pluginload
library database: /home/martijn/.config/beets/library.db
library directory: /home/martijn/beets-music
Sending event: library_opened
error: unknown command 'yearfixer'
```

**Comment by adamjakab** [comment]
Hi @MartenBE,
I guess this issue is long gone. Sorry for getting back to you so late.
Update to beets v1.6.0 and this error will be gone.
